// @ts-check
import eslint from "@eslint/js";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import globals from "globals";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: ["eslint.config.mjs"],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.vitest,
      },
      ecmaVersion: 5,
      sourceType: "module",
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      "@typescriptEslint/explicit-module-boundary-types": "off",
      "@typescriptEslint/no-inferrable-types": "off",
      "@typescriptEslint/no-non-null-assertion": "off",
      "@typescriptEslint/no-empty-interface": "off",
      "@typescriptEslint/no-namespace": "off",
      "@typescriptEslint/no-empty-function": "off",
      "@typescriptEslint/no-this-alias": "off",
      "@typescriptEslint/ban-types": "off",
      "@typescriptEslint/ban-ts-comment": "off",
      "@prefer-spread": "off",
      "@no-case-declarations": "off",
      "@no-console": "off",
      "@typescriptEslint/no-unused-vars": ["error"],
      "@typescriptEslint/consistent-type-imports": "warn",
      "@typescriptEslint/no-unnecessary-condition": "warn",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/no-unsafe-argument": "warn",
    },
    ignores: [
      "**/*.log",
      "**/.DS_Store",
      ".vscode/settings.json",
      ".history",
      ".yarn",
      "bazel-*",
      "bazel-bin",
      "bazel-out",
      "bazel-qwik",
      "bazel-testlogs",
      "dist",
      "dist-dev",
      "etc",
      "external",
      "node_modules",
      "temp",
      "tsc-out",
      "tsdoc-metadata.json",
      "target",
      "output",
      "rollup.config.js",
      "build",
      ".cache",
      ".vscode",
      ".rollup.cache",
      "tsconfig.tsbuildinfo",
      "vite.config.ts",
      "jest.config.ts",
      "eslint.config.js",
      "*.spec.tsx",
      "*.spec.ts",
      ".netlify",
      "pnpm-lock.yaml",
      "package-lock.json",
      "yarn.lock",
      "webpack.config.cjs",
      "*.mjs",
      "sst-env.d.ts",
      "sst.config.ts",
    ],
  },
  eslintConfigPrettier,
);
